kind: Service
apiVersion: v1
metadata:
  name: {{ .Values.appname }}
  labels:
    app: {{ .Values.appname }}
    source: cicd
spec:
  ports:
    - protocol: TCP
      port: {{ .Values.service.Port }}
      targetPort: {{ .Values.service.targetPort }}
  selector:
    app: {{ .Values.appname }}
  type: ClusterIP
  sessionAffinity: None
